server:
  port: 8846

spring:
  application:
    name: mym-user-authentication-service
  data:
    mongodb:
      uri: mongodb+srv://rkumar0205mym:mnirks0206@manageyourmoneycluster.dfkepd9.mongodb.net/?retryWrites=true&w=majority
      database: mym-user-db
  rabbitmq:
    port: 5672
    host: localhost
    username: mym_rkumar0206
    password: mym_password_123
    virtual-host: ${rabbitmqserver.env:mym-env-test}

myEureka:
  username: 'rkumar0206'
  password: '123456789P'

eureka:
  client:
    service-url:
      defaultZone: http://${myEureka.username}:${myEureka.password}@localhost:8845/eureka
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30

token:
  accessExpirationTimeDay: 1
  refreshExpirationTimeDay: 30
  issuer: rohitTheBest
  secret: abjabhvavvatttafgvctafcfXxFYTrtfytratrtyactyafhgavcghav__DBhevv$$$4

routing-keys:
  accountVerification: mym.user.account.verification
  emailUpdateOtp: mym.user.email.update.otp
  passwordReset: mym.user.password.reset

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
      base-path: "/mym/${spring.application.name}/actuator"